(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const setupPanel=$('setupPanel'),playPanel=$('playPanel'),playerCountEl=$('playerCount'),startBtn=$('startBtn'),restartBtn=$('restartBtn'),rulesBtn=$('rulesBtn'),rulesOverlay=$('rulesOverlay'),closeRules=$('closeRules'),roundText=$('roundText'),phaseText=$('phaseText'),scoreboard=$('scoreboard'),readyPanel=$('readyPanel'),readyIcon=$('readyIcon'),readyTitle=$('readyTitle'),readyBtn=$('readyBtn'),choosePanel=$('choosePanel'),chooseTitle=$('chooseTitle'),hand=$('hand'),confirmCardBtn=$('confirmCardBtn'),roundResultPanel=$('roundResultPanel'),roundResultTitle=$('roundResultTitle'),playedCards=$('playedCards'),roundWinnerText=$('roundWinnerText'),nextRoundBtn=$('nextRoundBtn'),finalResultPanel=$('finalResultPanel'),finalTitle=$('finalTitle'),finalScores=$('finalScores'),backSetupBtn=$('backSetupBtn');
  const RANKS=['A','K','Q','J','10'],POWER={A:5,K:4,Q:3,J:2,'10':1},SUITS=[{symbol:'♠',name:'スペード',red:false},{symbol:'♥',name:'ハート',red:true},{symbol:'♦',name:'ダイヤ',red:true},{symbol:'♣',name:'クラブ',red:false}];
  const store=globalThis.MiniGamePortalPlayerStore;
  let players=[],round=1,currentIndex=0,choices={},selected=null,reveal=false,recorded=false;
  function playerName(i){return `PLAYER ${i+1}`}
  function renderScores(){scoreboard.innerHTML='';players.forEach((p,i)=>{const d=document.createElement('div');d.className='score-item';d.innerHTML=`<span>${SUITS[i].symbol} ${playerName(i)}</span><b>${p.score}</b>`;scoreboard.appendChild(d)})}
  function start(){const count=Number(playerCountEl.value);reveal=document.querySelector('input[name="revealMode"]:checked').value==='open';players=Array.from({length:count},()=>({score:0,remaining:[...RANKS]}));round=1;currentIndex=0;choices={};selected=null;recorded=false;setupPanel.classList.add('hidden');playPanel.classList.remove('hidden');finalResultPanel.classList.add('hidden');roundResultPanel.classList.add('hidden');showReady()}
  function resetToSetup(){setupPanel.classList.remove('hidden');playPanel.classList.add('hidden');roundResultPanel.classList.add('hidden');finalResultPanel.classList.add('hidden')}
  function showReady(){roundText.textContent=`ROUND ${round} / 5`;phaseText.textContent='準備';renderScores();choosePanel.classList.add('hidden');roundResultPanel.classList.add('hidden');finalResultPanel.classList.add('hidden');readyPanel.classList.remove('hidden');readyIcon.textContent=SUITS[currentIndex].symbol;readyIcon.classList.toggle('red',SUITS[currentIndex].red);readyTitle.textContent=`${playerName(currentIndex)} の番です`;selected=null;confirmCardBtn.disabled=true}
  function showChoose(){readyPanel.classList.add('hidden');choosePanel.classList.remove('hidden');phaseText.textContent='カード選択';chooseTitle.textContent=`${SUITS[currentIndex].symbol} ${playerName(currentIndex)}：カードを1枚選択`;hand.innerHTML='';players[currentIndex].remaining.forEach(rank=>{const b=document.createElement('button');b.type='button';b.className=`playing-card${SUITS[currentIndex].red?' red':''}`;b.innerHTML=`<span class="rank">${rank}</span><span class="suit">${SUITS[currentIndex].symbol}</span><span class="rank">${rank}</span>`;b.addEventListener('click',()=>selectCard(rank,b));hand.appendChild(b)})}
  function selectCard(rank,button){selected=rank;[...hand.children].forEach(x=>x.classList.remove('selected'));button.classList.add('selected');confirmCardBtn.disabled=false}
  function confirmCard(){if(!selected)return;choices[currentIndex]=selected;players[currentIndex].remaining=players[currentIndex].remaining.filter(r=>r!==selected);selected=null;confirmCardBtn.disabled=true;choosePanel.classList.add('hidden');if(currentIndex<players.length-1){currentIndex++;showReady()}else{resolveRound()}}
  function resolveRound(){const max=Math.max(...Object.values(choices).map(r=>POWER[r]));const winners=Object.keys(choices).map(Number).filter(i=>POWER[choices[i]]===max);winners.forEach(i=>players[i].score++);renderScores();phaseText.textContent='勝負結果';roundResultTitle.textContent=`ROUND ${round} 結果`;playedCards.innerHTML='';players.forEach((p,i)=>{const wrap=document.createElement('div');wrap.className='played-card-wrap';const name=document.createElement('small');name.textContent=playerName(i);const card=document.createElement('div');card.className=`result-card${reveal&&SUITS[i].red?' red':''}${reveal?'':' back'}`;card.textContent=reveal?`${choices[i]} ${SUITS[i].symbol}`:'◆';if(winners.includes(i)){const tag=document.createElement('div');tag.className='winner-tag';tag.textContent='+1 POINT';wrap.append(name,card,tag)}else{wrap.append(name,card)}playedCards.appendChild(wrap)});roundWinnerText.textContent=winners.length===1?`${playerName(winners[0])} が+1ポイント`:`${winners.map(playerName).join('・')} が同率1位で全員+1ポイント`;readyPanel.classList.add('hidden');choosePanel.classList.add('hidden');roundResultPanel.classList.remove('hidden');nextRoundBtn.textContent=round>=5?'最終結果へ':'次のラウンドへ'}
  function nextRound(){if(round>=5){showFinal();return}round++;currentIndex=0;choices={};showReady()}
  function showFinal(){roundResultPanel.classList.add('hidden');finalResultPanel.classList.remove('hidden');phaseText.textContent='ゲーム終了';const top=Math.max(...players.map(p=>p.score));const winners=players.map((p,i)=>p.score===top?i:-1).filter(i=>i>=0);finalTitle.textContent=winners.length===1?`${playerName(winners[0])} の勝ち！`:`${winners.map(playerName).join('・')} の引き分け`;finalScores.innerHTML='';players.forEach((p,i)=>{const d=document.createElement('div');d.className='final-score';d.innerHTML=`<span>${SUITS[i].symbol} ${playerName(i)}</span><b>${p.score} POINT</b>`;finalScores.appendChild(d)});recordPlay()}
  function recordPlay(){if(recorded||!store)return;recorded=true;store.recordPlay('high-card','カード強さ勝負')}
  readyBtn.addEventListener('click',showChoose);confirmCardBtn.addEventListener('click',confirmCard);nextRoundBtn.addEventListener('click',nextRound);startBtn.addEventListener('click',start);restartBtn.addEventListener('click',resetToSetup);backSetupBtn.addEventListener('click',resetToSetup);rulesBtn.addEventListener('click',()=>rulesOverlay.classList.add('show'));closeRules.addEventListener('click',()=>rulesOverlay.classList.remove('show'));rulesOverlay.addEventListener('click',e=>{if(e.target===rulesOverlay)rulesOverlay.classList.remove('show')});
})();
