globalThis.MINI_GAME_PORTAL_GAMES = [
  {
    "schemaVersion": 1,
    "id": "baccarat",
    "name": "BACCARAT",
    "category": "casino",
    "categoryLabel": "CASINO",
    "description": "パラダイス実戦を想定したバカラ練習ゲーム。",
    "searchTerms": [
      "baccarat",
      "バカラ",
      "casino",
      "カジノ",
      "パラダイス",
      "練習"
    ],
    "icon": "./games/casino/baccarat/icon.svg",
    "entry": "./index.html",
    "available": true,
    "path": "./games/casino/baccarat/",
    "localEntry": "./games/casino/baccarat/index.html",
    "assets": [
      "./games/casino/baccarat/css/style.css",
      "./games/casino/baccarat/icon.svg",
      "./games/casino/baccarat/index.html",
      "./games/casino/baccarat/js/game.js"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "blackjack",
    "name": "BLACKJACK",
    "category": "casino",
    "categoryLabel": "CASINO",
    "description": "実戦を想定したブラックジャック練習ゲーム。",
    "searchTerms": [
      "blackjack",
      "ブラックジャック",
      "casino",
      "カジノ",
      "実戦",
      "練習"
    ],
    "icon": "./games/casino/blackjack/icon.svg",
    "entry": "./index.html",
    "available": true,
    "path": "./games/casino/blackjack/",
    "localEntry": "./games/casino/blackjack/index.html",
    "assets": [
      "./games/casino/blackjack/css/style.css",
      "./games/casino/blackjack/icon.svg",
      "./games/casino/blackjack/index.html",
      "./games/casino/blackjack/js/game.js"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "flash-rush",
    "name": "FLASH RUSH",
    "category": "action",
    "categoryLabel": "ACTION",
    "description": "100種類の瞬間ミニゲームをハイテンポで連続攻略。",
    "searchTerms": [
      "flash rush",
      "フラッシュラッシュ",
      "瞬間ゲーム",
      "ミニゲーム",
      "アクション",
      "action",
      "micro game"
    ],
    "icon": "./games/action/flash-rush/icon.svg",
    "entry": "./index.html",
    "available": true,
    "path": "./games/action/flash-rush/",
    "localEntry": "./games/action/flash-rush/index.html",
    "assets": [
      "./games/action/flash-rush/css/style.css",
      "./games/action/flash-rush/icon.svg",
      "./games/action/flash-rush/index.html",
      "./games/action/flash-rush/js/game.js"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "laser-escape",
    "name": "LASER ESCAPE",
    "category": "action",
    "categoryLabel": "ACTION",
    "description": "迫りくるレーザーを避け続けるドット絵サバイバル。",
    "searchTerms": [
      "laser escape",
      "レーザーエスケープ",
      "レーザー",
      "回避",
      "サバイバル",
      "ドットゲーム",
      "アクション",
      "action",
      "survival"
    ],
    "icon": "./games/action/laser-escape/icon.svg",
    "entry": "./index.html",
    "available": true,
    "path": "./games/action/laser-escape/",
    "localEntry": "./games/action/laser-escape/index.html",
    "assets": [
      "./games/action/laser-escape/css/style.css",
      "./games/action/laser-escape/icon.svg",
      "./games/action/laser-escape/index.html",
      "./games/action/laser-escape/js/game.js"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "roulette",
    "name": "ROULETTE",
    "category": "casino",
    "categoryLabel": "CASINO",
    "description": "今後追加予定。",
    "searchTerms": [
      "roulette",
      "ルーレット",
      "casino",
      "カジノ"
    ],
    "icon": "./games/casino/roulette/icon.svg",
    "entry": "./index.html",
    "available": false,
    "path": "./games/casino/roulette/",
    "localEntry": "./games/casino/roulette/index.html",
    "assets": [
      "./games/casino/roulette/icon.svg"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "yukyo-no-yakata",
    "name": "幽鏡の館",
    "category": "adventure",
    "categoryLabel": "ADVENTURE",
    "description": "呪われた館を探索し、謎を解きながら鏡に潜む怪異から逃れる探索ホラー。",
    "searchTerms": [
      "幽鏡の館",
      "ゆうきょうのやかた",
      "ホラー",
      "horror",
      "謎解き",
      "探索",
      "脱出",
      "幽霊",
      "怪異",
      "adventure",
      "アドベンチャー"
    ],
    "icon": "./games/adventure/yukyo-no-yakata/icon.svg",
    "entry": "./index.html",
    "available": true,
    "path": "./games/adventure/yukyo-no-yakata/",
    "localEntry": "./games/adventure/yukyo-no-yakata/index.html",
    "assets": [
      "./games/adventure/yukyo-no-yakata/README.txt",
      "./games/adventure/yukyo-no-yakata/assets/ghost/closeup.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/down_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/down_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/down_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/left_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/left_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/left_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/right_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/right_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/right_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/up_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/up_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/ghost/up_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/down_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/down_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/down_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/left_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/left_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/left_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/right_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/right_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/right_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/up_0.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/up_1.webp",
      "./games/adventure/yukyo-no-yakata/assets/hero/up_2.webp",
      "./games/adventure/yukyo-no-yakata/assets/rooms/basement.webp",
      "./games/adventure/yukyo-no-yakata/assets/rooms/bath.webp",
      "./games/adventure/yukyo-no-yakata/assets/rooms/bedroom.webp",
      "./games/adventure/yukyo-no-yakata/assets/rooms/corridor.webp",
      "./games/adventure/yukyo-no-yakata/assets/rooms/mirror.webp",
      "./games/adventure/yukyo-no-yakata/assets/rooms/parlor.webp",
      "./games/adventure/yukyo-no-yakata/assets/rooms/study.webp",
      "./games/adventure/yukyo-no-yakata/assets/ui/title.webp",
      "./games/adventure/yukyo-no-yakata/css/style.css",
      "./games/adventure/yukyo-no-yakata/icon.svg",
      "./games/adventure/yukyo-no-yakata/index.html",
      "./games/adventure/yukyo-no-yakata/js/game.js"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "marubatsu",
    "name": "消える○×ゲーム",
    "category": "board",
    "categoryLabel": "ボードゲーム",
    "description": "4個目を置くと一番古いコマが消える三目並べ。",
    "searchTerms": [
      "消える○×ゲーム",
      "まるばつ",
      "マルバツ",
      "○×",
      "tic tac toe",
      "三目並べ",
      "board",
      "ボードゲーム"
    ],
    "icon": "./games/board/marubatsu/icon.svg",
    "entry": "./index.html",
    "available": true,
    "path": "./games/board/marubatsu/",
    "localEntry": "./games/board/marubatsu/index.html",
    "assets": [
      "./games/board/marubatsu/css/style.css",
      "./games/board/marubatsu/icon.svg",
      "./games/board/marubatsu/index.html",
      "./games/board/marubatsu/js/game.js"
    ]
  }
];
